services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_dist:/app/dist
    ports:
      - "8443:8443"
    networks:
      - App

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - App

volumes:
  frontend_dist:

networks:
  App:
    driver: bridge