services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8443:8443"
    networks:
      - App

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - App

networks:
  App:
    driver: bridge